site_name: 'nttdata_prueba01'
site_description: 'nttdata_prueba01nttdata_prueba01nttdata_prueba01nttdata_prueba01nttdata_prueba01nttdata_prueba01'

repo_url: https://github.com/DHermoso/nttdata_prueba01/
edit_uri: blob/master/docs/

nav:
  - Home: index.md
  - readme1: readme1.md
  - kafka_monitorizacion: kafka_monitorizacion.md
  - Kafka_eHodei_encriptacion: Kafka_eHodei_encriptacion.md
  - Kafka_eHodei_acceso: Kafka_eHodei_acceso.md
  - kafka_conector_mongodb: kafka_conector_mongodb.md
