site_name: 'nttdata_prueba01'
site_description: 'nttdata_prueba01nttdata_prueba01nttdata_prueba01nttdata_prueba01nttdata_prueba01nttdata_prueba01'

repo_url: https://github.com/DHermoso/nttdata_prueba01/
edit_uri: blob/master/docs/

nav:
  - Home: readme1.md
