site_name: 'nttdata_prueba01'
site_description: 'nttdata_prueba01nttdata_prueba01nttdata_prueba01nttdata_prueba01nttdata_prueba01nttdata_prueba01'

repo_url: https://github.com/DHermoso/nttdata_prueba01/
edit_uri: blob/master/docs/

nav:
  - Home: index.md
  - readme1: readme1.md
  - kafka_monitorizacion: kafka_monitorizacion.md
  - Kafka_eHodei_encriptacion: Kafka_eHodei_encriptacion.md
  - Kafka_eHodei_acceso: Kafka_eHodei_acceso.md
  - kafka_conector_mongodb: kafka_conector_mongodb.md

markdown_extensions:
  - footnotes

# Habilitamos la generacion de la documentacion como PDF
plugins:
  - search
  # Mermaid para diagramas
  - mermaid2
  # Habilitamos la generacion de la documentacion como PDF
  # - pdf-export:
  #    combined: true
  #    combined_output_path: pdf/kafka_v1.0.pdf
  # https://pypi.org/project/mkdocs-with-pdf/
  - with-pdf:
      copyright: Copyright &copy; 2021 Eusko Jaurlaritzaren Informatika Elkartea (EJIE)
      cover_subtitle: Documentaci&oacute;n del producto

theme:
  name: material
  features:
       - content.tabs.link
